name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  specs:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update -qq && sudo apt-get install libpcap-dev -qq
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run specs
      run: |
        bundle config set path vendor/bundle
        bundle config --set local without develoment rubocop
        bundle config --set local with test
        bundle install
        bundle exec rake spec

  sudo_specs:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update -qq && sudo apt-get install libpcap-dev -qq
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install gems
      run: |
        sudo gem install bundler --no-document
        sudo bundle config set path 'vendor/bundle'
        sudo bundle config set --local with test
        sudo bundle config --set local without develoment rubocop
        sudo bundle install
    - name: Run specs
      run: |
        sudo bundle exec rake spec:sudo
