name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  specs:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7.4'
          - '3.0'
          - '3.1'
          - '3.2'

    env:
      BUNDLE_ONLY: "test"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rake spec

  sudo_specs:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7.4'
          - '3.0'
          - '3.1'
          - '3.2'

    env:
      BUNDLE_ONLY: "test"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install gems
      run: |
        sudo gem install bundler --no-document
        sudo bundle config set path 'vendor/bundle'
        sudo bundle config set --local with test
        sudo bundle install

    - name: Run specs
      run: sudo bundle exec rake spec:sudo
